In [2]:
import numpy as np

The basics

In [3]:
a = np.array([1,2,3,4], dtype='int16')
print(a)

[1 2 3 4]


In [4]:
b = np.array([[1,2,3],[1,2,3]], dtype='int16')
print(b)

[[1 2 3]
 [1 2 3]]


In [5]:
b.ndim # get the number of dimensions

2

In [6]:
b.shape # get the structure of the array as (rows, cols)

(2, 3)

In [7]:
b.dtype # get the type fo array

dtype('int16')

In [8]:
# Get size
a.size # length
a.itemsize # item bytes
a.nbytes # item bytes * length

8

Accessing/Changing specific elements, rows, columns, etc

In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
# get specific element using [row, col]
a[1,3]

11

In [11]:
# get specific row 
a[0,:] # means get all cols for 0 row

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
# get specific col 
a[:, 0] # means get all rows for col 0

array([1, 8])

In [13]:
a[0, 1:6:2] # [row, startColIndex:endColIndex:stepSize]  

array([2, 4, 6])

In [14]:
a[0,0] = 2 # change specific element
a[0,:] = 5 # change specific row to be equal 5
a[:,0] = [1,2] # change specific col to be equal [1,2]
print(a)

[[ 1  5  5  5  5  5  5]
 [ 2  9 10 11 12 13 14]]


3D Example

In [15]:
b = np.array([[[1,2], [3,4], [4,5]], [[6,7], [8,9], [10,11]]])
print(b)

[[[ 1  2]
  [ 3  4]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [16]:
# change specific element 
b[1,0,0] = -6
print(b)

[[[ 1  2]
  [ 3  4]
  [ 4  5]]

 [[-6  7]
  [ 8  9]
  [10 11]]]


Initialize different types of array

In [17]:
# initialize all elements by 0
a = np.zeros(2 , dtype='int16') # shape, dtype
print(a)

[0 0]


In [18]:
# initialize all elements by 1
a = np.ones((2,2), dtype='int16') # shape, dtype
print(a)

[[1 1]
 [1 1]]


In [19]:
# initialize all element by specific number
a = np.full((2,3), 4 , dtype='int16') # shape, specific number, dtype
print(a)

[[4 4 4]
 [4 4 4]]


In [20]:
# we can also use 
a = np.full(b.shape, 4)
a = np.full_like(b, 4)
print(a)

[[[4 4]
  [4 4]
  [4 4]]

 [[4 4]
  [4 4]
  [4 4]]]


In [21]:
# Random decimal numbers
np.random.rand(2,3)

array([[0.56335031, 0.48613548, 0.41345804],
       [0.06469709, 0.86924765, 0.89807187]])

In [23]:
# Random integer numbers
np.random.randint(5,7, size=(2,5))

array([[6, 5, 6, 5, 5],
       [5, 5, 6, 6, 5]])